
services:
  database:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: symfony-practise-db
      POSTGRES_PASSWORD: abc123
      POSTGRES_USER: admin
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - published: 5432
        target: 5432
        protocol: tcp

  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - '9000:9000'
    depends_on:
      - database

  caddy:
    image: caddy:2
    volumes:
      - .:/var/www/html
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "8080:80"
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
  database_data: